### ISSUE TITLE
maxItemsPerPage doesn't work on StoreFront and blocks.

### ISSUE THREAD

**Issue by Gatamura** [vtex-apps/search-result#130]
## Expected Behavior

Ao tentar passar as props pelo blocks tanto dentro do objeto querySchema quanto fora o componente parece não respeitar esse número, possuí o mesmo comportamento no StoreFront.

**Comment by rerissondaniel** [comment]
@Gatamura Tenta passar mais uma propriedade no querySchema: `enableCustomQuery: true`, por favor.

**Comment by Gatamura** [comment]
@rerissondaniel Funcionou porém surgiram alguns efeitos colaterais, sumiu o conteúdo do breadcrumb e também os filtros ao adicionar essa propriedade. Consegue nos ajudar com isso ?

**Comment by mica-acct** [comment]
@rerissondaniel realmente ao colocar o parâmetro, acaba quebrando filtros, hover, entre outros itens.
Consegue nos ajudar neste ponto?

**Comment by GabrielTamuraACCT** [comment]
@rerissondaniel resolvido, somente precisamos alterar os atributos da props utilizando:

```
"props": {
    "context": {
        "maxItemsPerPage": 16,
        "orderByField": "OrderByReleaseDateDESC"
    }
}
```

**Comment by thiagoBHS** [comment]
Como isso foi resolvido? Coloquei como "context" (a unica diferença que vi) e continua aplicando apenas 10 produtos por página.

**Comment by thiagoBHS** [comment]
> @rerissondaniel resolvido, somente precisamos alterar os atributos da props utilizando:
> 
> ```
> "props": {
>     "context": {
>         "maxItemsPerPage": 16,
>         "orderByField": "OrderByReleaseDateDESC"
>     }
> }
> ```

Tentei aqui usar o "context" e não funcionou. Continua assim?
