### ISSUE TITLE
Change Collapse behavior so that only one filter is open

### ISSUE THREAD

**Issue by Erislandio** [vtex-apps/search-result#381]
**Is your feature request related to a problem? Please describe.**
When we click on a filter that has a Collapse, we see that it is possible to open several at the same time

* When we open several filters at the same time, depending on the layout to be followed, the filters are overlapping
Example: https://www.awesomescreenshot.com/video/298755?key=30bdada05f19cc03a0c708d218f20971

**Describe the solution you'd like**
A solution would be a property that can be passed to the filter, or a change in the way the component's state is being managed: FilterOptionTemplate, adding some kind of context to the filters

**Additional context**
Example of how it would look:
https://www.tokstok.com.br/acessorios

See that only one filter is currently open

**Comment by alextalha** [comment]
@iaronaraujo   @klzns @victorhmp 
I'm having the same problem

**Comment by ricardo7634234** [comment]
Please check this PR.
https://github.com/vtex-apps/search-result/pull/397

**Comment by iaronaraujo** [comment]
Solved! @Erislandio @alextalha @ricardo7634234
