### ISSUE TITLE
Page scrollable when accordionFilters is open

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/search-result#382]
**Describe the bug**
On the search page, Mobile device, when you click on "filter", the drawer with the filters appears. It adds the class "overflow-hidden-ns" to the body (which is correct) but the class is not defined. Because of this, you can scroll the page when the filter drawer is open, but you cannot scroll the filters.

**To Reproduce**

1. Go to category page (mobile)
2. Click on "filter"
3. Try to scroll the filter area

**Expected behavior**
Class overflow-hidden-ns should be defined with overflow:hidden and height 100vh to prevent the page scroll while the filters are visible

**Screenshots**
![image](https://user-images.githubusercontent.com/42587916/86120066-529fd780-badc-11ea-85e3-1c9b835049eb.png)

Press filter while on mobile in this workspace: https://develop--dacris.myvtex.com/articole-de-birou/organizare-si-arhivare/bibliorafturi

**Comment by chrsmutti** [comment]
Closed, was unable to reproduce on the latest version.

https://user-images.githubusercontent.com/34144667/113188781-dd129480-9230-11eb-8831-cb50335a1d1c.mov
