### ISSUE TITLE
hideUnavailableItems not working

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/search-result#425]
**Describe the bug**
Although the prop is used in the search context, unavailable items are still showing.

**To Reproduce**

Use following code:

`"store.search#category": {
    "blocks": ["search-result-layout"],
    "props": {
      "context": {
        "maxItemsPerPage": 36,
        "skusFilter": "ALL",
        "simulationBehavior": "skip",
        "__unstableProductOriginVtex":true,
        "hideUnavailableItems":true
      }
    }
  },
`
Prop is added to all interfaces (category, department, brand, subcategory)

Test url: https://supermercato.myvtex.com/produse-de-cur%C4%83%C8%9Benie (see row 4, column 3, product "Degresant Chanteclair Universal Marsiglia 5L"

**Expected behavior**
Unavailable items should be hidden from search-results.

**Screenshots**
![image](https://user-images.githubusercontent.com/42587916/93069845-cc307600-f686-11ea-9d2e-f4739a4e2554.png)

**Desktop environment:**

System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.72 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 76.0.1
    Safari: 13.1.2

Thank you!

**Comment by chrsmutti** [comment]
Hi @doruradu, I wasn't able to reproduce it anymore. We'll look into it on our side, if you find any other cases let us know so that it can expedite the debugging process.
