### ISSUE TITLE
Clear filters & Apply redirects to homepage

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/search-result#449]
**Describe the bug**
If I open the filters on the listing page **on mobile** and I press "Clear filters" button and "Apply", it redirects me to homepage with the following parameters **?fuzzy=0&operator=and**

**To Reproduce**

1. Go to distinctive.myvtex.com/Femei/Imbracaminte
2. Click on 'Filtreaza'
3. Click on 'Sterge Filtre'
4. Click on 'Aplica'

**Expected behavior**
Refresh the page without any active filters.

**Comment by chrsmutti** [comment]
This was fixed, the behavior now is returning to the initial query (in the case of the reproduce steps, it stays on the same page).
