### ISSUE TITLE
Collections - Page title issue

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/search-result#461]
**Describe the bug**
On the product listing page, when you filter by a collection, the title of the collection is displayed in the page title, instead of its name.

https://www.distinctive.ro/184?map=productClusterIds&order=OrderByScoreDESC

**To Reproduce**

1. Go to distinctive.ro
2. Click on Femei/Barbati/Fete/Baieti/Casa & Deco in menu
3. Click on Outlet
4. See the page title

**Expected behavior**
The collections name should appear as page title.

**Comment by hiagolcm** [comment]
It is a known issue. 😞 
The fix is in our backlog. I will let you know when it is done.

**Comment by khrizzcristian** [comment]
Fixed?

**Comment by chrsmutti** [comment]
@khrizzcristian I may be mixing up some of our internal issue tracking, but this was related to the name of the collection not appearing on the page title?

![image](https://user-images.githubusercontent.com/34144667/113187869-b99b1a00-922f-11eb-9dbe-4b85469d1c1e.png)

That's the expected page title for the link you sent or am I missing something?
