### ISSUE TITLE
Sort Issues ( Best Discount & Price )

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/search-result#499]
**Describe the bug**
Hello. We have 2 problems with sorting on the website https://distinctive.ro

**1. Order by Price DESC**
Everything works correctly on the category page (ex: https://www.distinctive.ro/Femei/Incaltaminte?order=OrderByPriceDESC). The ordering is done accordingly, according to the final price.

If we select a filter (Brand> Sketchers), the sorting is done according to the initial price.
URL: https://www.distinctive.ro/femei/incaltaminte/skechers?initialMap=c,c&initialQuery=femei/incaltaminte&map=category-1,category-2,brand&order=OrderByPriceDESC

**2. Order By Best Discount**

It also works properly on the category page
URL: https://www.distinctive.ro/Femei/Incaltaminte?order=OrderByBestDiscountDESC

If we select a filter (Brand> Sketchers), there are products that have no discount among the discount products.

**To Reproduce**

1. Go to https://www.distinctive.ro/
2. Select Femei > Incaltaminte
3. Click on "Sorteaza" and select "Discount" or "Cel mai mare pret"
4. See the results ( all good here )
5. Select "Brand > Skechers" from filters
6. See the results

**Screenshot -> OrderByBestDiscount**
![BestDiscount](https://user-images.githubusercontent.com/43498488/113105411-387d5c00-920a-11eb-9e48-51df646e6bec.jpg)

**Screenshot -> OrderByPriceDESC**
![Price](https://user-images.githubusercontent.com/43498488/113105417-3915f280-920a-11eb-8f19-1d564c5ce97c.jpg)

**Comment by khrizzcristian** [comment]
Hello.
Indeed, I see that everything is functional now.

 I have a question, though. This problem was reported by the client on Monday, and I still managed to reproduce it this morning.

Shouldn't indexing take less time?

**Comment by chrsmutti** [comment]
Yes, indexing takes significantly less time than that. I can't say for sure what would be the issue, and that could take some investigation, which could be done via a support ticket for the Search & Personalization support team.

I'll close this issue, but thanks again for the detailed report, it helps a lot as we'll be taking better care of Github issues from now on!
