### ISSUE TITLE
Filter items in alphabetical order

### ISSUE THREAD

**Issue by trewous** [vtex-apps/search-result#529]
**Is your feature request related to a problem? Please describe.**
Yes, many clients requests this, it will be easier for customers to see filter items in order.

**Describe the solution you'd like**
Filter items in Filter Navigator to be displayed in alphabetical order.

**Comment by trewous** [comment]
Closing beacause it was implemented. Thanks!

**Comment by cristianmarcet** [comment]
Hi.
Could you provide me documentation about this feature please?
We have a client who asks us to be able to perform custom ordering of categories and subcategories that appear in the search results filters.
